### ISSUE TITLE
Doesn't work on Arduino Version 2.0.0

### ISSUE THREAD

**Issue by JohnKun136NVCP** [me-no-dev/arduino-esp32fs-plugin#40]
Following your steps and installing ESP32 on my computer (Windows).
Arduino upper version as 2.0.0 doesn't work.
Arduino lower version as 2.0.0 works.

**Comment by fermintm** [comment]
Arduino 2.0 does not support SPIFFS Upload

**Comment by Will-wastelander** [comment]
Fresh install of 2.1.1 and this tool does not work.
