### ISSUE TITLE
Latest Arduino ESP32 1.0.1 rc2 doesn't work with the tool

### ISSUE THREAD

**Issue by robertgregor** [me-no-dev/arduino-esp32fs-plugin#9]
There is seems issue to upload SPIFFS. What can be the problem?

[SPIFFS] upload : C:\Users\gregorro\AppData\Local\Temp\arduino_build_361363/TestAsync.spiffs.bin
[SPIFFS] address: 2691072
[SPIFFS] port   : COM4
[SPIFFS] speed  : 256000
[SPIFFS] mode   : dio
[SPIFFS] freq   : 80m

error: Invalid argument or value after --chip (argument #2)

**Comment by Menion2k** [comment]
Same issue here

**Comment by d0ct0rd-dalimo** [comment]
The same issue

**Comment by me-no-dev** [comment]
fixed in the latest release yesterday :)

**Comment by ivangoda** [comment]
The same issue today

**Comment by bernd1950** [comment]
Same issue with wemos LOLIN32:
error: Invalid argument or value after --chip (argument #2)
